name: SisKa
description: Sistem Informasi Kemajuan Akademik Pascasarjana Undiksha

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.4+5

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  line_icons: 0.2.0


  back_button_interceptor: 4.2.3  # INITIAL
#  back_button_interceptor: ^4.2.4  # Incompatible w/ this flutter version
#  back_button_interceptor: ^4.3.1  # Incompatible w/ this flutter version
  badges: 1.1.1 # INITIAL
#  badges: ^1.1.3  # Incompatible w/ this flutter version
  charts_flutter: 0.9.0  # INITIAL
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: 0.1.3 # INITIAL
#  cupertino_icons: ^1.0.0 # Incompatible w/ this flutter version
  firebase_messaging: 5.1.8  # INITIAL
#  firebase_messaging: ^7.0.3	# ?
  floating_ribbon: 1.0.1 # INITIAL
  flushbar: 1.9.1 # INITIAL
#  flushbar: ^1.10.4 # ?
  flutter_html: 0.11.1	# INITIAL
#  flutter_html: ^1.0.2	# Incompatible w/ flutter_plugin_pdf_viewer: ^1.0.7
  flutter_plugin_pdf_viewer: 1.0.7 # INITIAL
  flutter_slidable: 0.5.4  # INITIAL
#  flutter_slidable: ^0.5.7 # ?
  flutter_statusbarcolor: 0.2.3  # INITIAL
  flutter_widget_from_html_core: 0.3.3+4	# INITIAL
#  flutter_widget_from_html_core: ^0.5.1	# Incompatible w/ this flutter version
  gradient_text: 1.0.2 # INITIAL
  http: 0.12.1 # INITIAL
#  http: ^0.12.2  # ?
  image_picker: 0.6.7  # INITIAL
#  image_picker: ^0.6.7+11 # https://github.com/flutter/flutter/issues/58479 (use Gradle plugin 3.6.4!)
  modal_progress_hud: 0.1.3 # INITIAL
  progress_hud: 1.1.0  # INITIAL
  searchable_dropdown: 1.1.3 # INITIAL
  shared_preferences: 0.5.7+3 # INITIAL
#  shared_preferences: ^0.5.12 # https://github.com/flutter/flutter/issues/58479 (use Gradle plugin 3.6.4!)
  skeleton_text: 1.0.0 # INITIAL
  splashscreen: 1.2.0  # INITIAL
  timeline_list: 0.0.5 # INITIAL
  url_launcher: 5.4.10 # INITIAL
#  url_launcher: ^5.4.11  # ?
#  url_launcher: ^5.7.2 # ?

dev_dependencies:
  flutter_launcher_icons: 0.7.5  # INITIAL
#  flutter_launcher_icons: ^0.8.0  # ?
#  flutter_launcher_icons: ^0.8.1  # Incompatible w/ this flutter version
  flutter_test:
    sdk: flutter
  

flutter_icons:
    android: "launcher_icon" 
    ios: true
    image_path_ios: "assets/images/LogoUndiksha.png" 
    image_path_android: "assets/images/LogoUndiksha.png" 
    




# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
#   - assets/images/man1.jpg
#   - assets/images/man2.jpg
#   - assets/images/man3.jpg
#   - assets/images/man4.jpg
#   - assets/images/man5.jpg
#   - assets/images/woman1.jpg
#   - assets/images/woman2.jpg
#   - assets/images/woman3.jpg
#   - assets/images/woman4.jpg
#   - assets/images/woman5.jpg
   - assets/images/home_page.png
   - assets/images/logo.png
   - assets/images/empty.png
   - assets/images/LogoUndiksha.png
   - assets/images/LogoUndiksha1.png
   - assets/images/post_banner.jpg
   - assets/images/error.png
   - assets/images/notfound.png
   - assets/images/nodata.png
   - assets/images/notfound.gif

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Barlow
      fonts:
        - asset: assets/fonts/Barlow-Regular.ttf
        - asset: assets/fonts/Barlow-SemiBold.ttf
          weight: 400
        - asset: assets/fonts/Barlow-Bold.ttf
          weight: 700
    - family: Quicksand
      fonts:
        - asset: assets/fonts/Quicksand-Regular.ttf
        - asset: assets/fonts/Quicksand-Medium.ttf
        - asset: assets/fonts/Quicksand-SemiBold.ttf
        - asset: assets/fonts/Quicksand-Bold.ttf
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
